<?php

$labels = array();
$labels['keyboard_shortcuts'] = 'Keyboard shortcuts';
$labels['all'] = 'General Shortcuts';
$labels['mail'] = 'Mail';
$labels['title'] = 'Keyboard Shortcuts';
$labels['keyexists'] = 'This key is already in use';
$labels['invalidkey'] = 'This key is not supported';
$labels['multiple_modifiers'] = 'Combinations of shift/ctrl/alt are not supported';

/**
 * commands
 */
$labels['help'] = 'Show shortcuts';
$labels['select-page'] = 'Select all messages on page';
$labels['select-all'] = 'Select all messages';
$labels['select-flagged'] = 'Select flagged messages';
$labels['select-invert'] = 'Invert message selection';
$labels['select-none'] = 'Deselect messages';
$labels['select-unread'] = 'Select unread messages';
$labels['mark-flagged'] = 'Mark messages as flagged';
$labels['mark-unflagged'] = 'Mark messages as unflagged';
$labels['mark-read'] = 'Mark messages as read';
$labels['mark-unread'] = 'Mark messages as unread';

/**
 * header message
 */
$messages = array();
$messages['header'] = 'You can configure shortcuts for each section in roundcube. Global shortcuts work in all sections';

?>
