<?php

$labels = array();
$labels['keyboard_shortcuts'] = 'Keyboard shortcuts';
$labels['global'] = 'Global Shortcuts';
$labels['show'] = 'Message view';
$labels['mailbox'] = 'Mailbox View';
$labels['title'] = 'Keyboard Shortcuts';
$labels['keyexists'] = 'This key is already in use';
$labels['invalidkey'] = 'This key is not allowed';

// commands
$labels['ks_help'] = 'Help';
$labels['ks_selectallvisiblemessages'] = 'Select all visible messages';
$labels['ks_markallvisiblemessagesasread'] = 'Mark all visible messages as read';

$messages = array();
$messages['header'] = 'You can configure shortcuts for each section in roundcube. Global shortcuts work in all sections';

?>
